# Generated by Django 4.1 on 2022-09-19 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saifapp', '0003_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='article',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
