# Generated by Django 4.1 on 2022-09-22 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saifapp', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
