# Generated by Django 4.1 on 2022-09-29 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saifapp', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
