# Generated by Django 4.1 on 2022-10-02 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saifapp', '0011_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='img_article',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
