# Generated by Django 4.1 on 2022-10-02 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saifapp', '0013_article_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.TextField()),
                ('line_number', models.IntegerField()),
                ('img_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saifapp.article')),
            ],
        ),
    ]
