# Generated by Django 4.1.2 on 2022-10-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('national_number', models.CharField(max_length=12)),
                ('grade', models.CharField(choices=[('FST', 'First'), ('SND', 'Second')], default='FST', max_length=30)),
                ('specialization', models.CharField(choices=[('Scientific', 'Scientific'), ('Literary', 'Literary'), ('Industrial', 'Industrial')], max_length=30)),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=30)),
            ],
        ),
    ]
