# Generated by Django 4.1.2 on 2022-10-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('national_number', models.CharField(max_length=12)),
                ('supervisor_for_grade', models.CharField(choices=[('Scientific FST A', 'Scientific FST A'), ('Literary FST A', 'Literary FST A'), ('Industrial FST A', 'Industrial FST A'), ('Scientific SND A', 'Scientific SND A'), ('Literary SND A', 'Literary SND A'), ('Industrial SND A', 'Industrial SND A'), ('Scientific FST B', 'Scientific FST B'), ('Literary FST B', 'Literary FST B'), ('Industrial FST B', 'Industrial FST B'), ('Scientific SND B', 'Scientific SND B'), ('Literary SND B', 'Literary SND B'), ('Industrial SND B', 'Industrial SND B'), ('Scientific FST C', 'Scientific FST C'), ('Literary FST C', 'Literary FST C'), ('Industrial FST C', 'Industrial FST C'), ('Scientific SND C', 'Scientific SND C'), ('Literary SND C', 'Literary SND C'), ('Industrial SND C', 'Industrial SND C'), ('Scientific FST D', 'Scientific FST D'), ('Literary FST D', 'Literary FST D'), ('Industrial FST D', 'Industrial FST D'), ('Scientific SND D', 'Scientific SND D'), ('Literary SND D', 'Literary SND D'), ('Industrial SND D', 'Industrial SND D'), ('Scientific FST E', 'Scientific FST E'), ('Literary FST E', 'Literary FST E'), ('Industrial FST E', 'Industrial FST E'), ('Scientific SND E', 'Scientific SND E'), ('Literary SND E', 'Literary SND E'), ('Industrial SND E', 'Industrial SND E'), ('Scientific FST F', 'Scientific FST F'), ('Literary FST F', 'Literary FST F'), ('Industrial FST F', 'Industrial FST F'), ('Scientific SND F', 'Scientific SND F'), ('Literary SND F', 'Literary SND F'), ('Industrial SND F', 'Industrial SND F')], max_length=200)),
                ('stuff', models.CharField(max_length=100)),
            ],
        ),
    ]
